// <auto-generated />
using System;
using BellaSposaBridal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BellaSposaBridal.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526210000_AddHeroVideosToAtlierInfo")]
    partial class AddHeroVideosToAtlierInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.AppointmentFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("AppointmentFiles");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.AppointmentTypeConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MainDescription")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("AppointmentTypeConfigs");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.AppointmentViewedDress", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DressId")
                        .HasColumnType("uuid");

                    b.HasKey("AppointmentId", "Order");

                    b.HasIndex("DressId");

                    b.ToTable("AppointmentViewedDresses");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.AtlierInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AppointmentRequired")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FittingDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("HeroVideoDesktop")
                        .HasColumnType("text");

                    b.Property<string>("HeroVideoMobile")
                        .HasColumnType("text");

                    b.Property<string>("Instagram")
                        .HasColumnType("text");

                    b.Property<bool>("IsFittingFree")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telegram")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("VipPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("text");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AtlierInfos");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FeaturedOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Season")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.DaySchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomSlots")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DaySchedules");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.Dress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CorsetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CustomTailoringAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Decoration")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasSleeves")
                        .HasColumnType("boolean");

                    b.Property<int>("HomepageFeaturedOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHomepageFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SilhouetteId")
                        .HasColumnType("integer")
                        .HasColumnName("Silhouette");

                    b.Property<string>("SleeveDescription")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TrainDescription")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SilhouetteId");

                    b.ToTable("Dresses");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.DressCollection", b =>
                {
                    b.Property<Guid>("DressId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("NavOrder")
                        .HasColumnType("integer");

                    b.HasKey("DressId", "CollectionId");

                    b.HasIndex("CollectionId");

                    b.ToTable("DressCollections");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.DressPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DressId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DressId");

                    b.ToTable("DressPhotos");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.DressSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DressId")
                        .HasColumnType("uuid");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DressId");

                    b.ToTable("DressSizes");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.DressVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DressId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DressId");

                    b.ToTable("DressVideos");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.RelatedDress", b =>
                {
                    b.Property<Guid>("DressId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RelatedDressId")
                        .HasColumnType("uuid");

                    b.HasKey("DressId", "RelatedDressId");

                    b.HasIndex("RelatedDressId");

                    b.ToTable("RelatedDresses");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.SilhouetteType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("SilhouetteTypes");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.TimeSlotConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.ToTable("TimeSlotConfigs");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.AppointmentFile", b =>
                {
                    b.HasOne("BellaSposaBridal.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Files")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.AppointmentViewedDress", b =>
                {
                    b.HasOne("BellaSposaBridal.Domain.Entities.Appointment", "Appointment")
                        .WithMany("ViewedDresses")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BellaSposaBridal.Domain.Entities.Dress", "Dress")
                        .WithMany()
                        .HasForeignKey("DressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Appointment");

                    b.Navigation("Dress");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.Dress", b =>
                {
                    b.HasOne("BellaSposaBridal.Domain.Entities.SilhouetteType", "SilhouetteType")
                        .WithMany("Dresses")
                        .HasForeignKey("SilhouetteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SilhouetteType");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.DressCollection", b =>
                {
                    b.HasOne("BellaSposaBridal.Domain.Entities.Collection", "Collection")
                        .WithMany("DressCollections")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BellaSposaBridal.Domain.Entities.Dress", "Dress")
                        .WithMany("Collections")
                        .HasForeignKey("DressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Dress");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.DressPhoto", b =>
                {
                    b.HasOne("BellaSposaBridal.Domain.Entities.Dress", "Dress")
                        .WithMany("Photos")
                        .HasForeignKey("DressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dress");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.DressSize", b =>
                {
                    b.HasOne("BellaSposaBridal.Domain.Entities.Dress", "Dress")
                        .WithMany("Sizes")
                        .HasForeignKey("DressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dress");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.DressVideo", b =>
                {
                    b.HasOne("BellaSposaBridal.Domain.Entities.Dress", "Dress")
                        .WithMany("Videos")
                        .HasForeignKey("DressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dress");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.RelatedDress", b =>
                {
                    b.HasOne("BellaSposaBridal.Domain.Entities.Dress", "Dress")
                        .WithMany("RelatedDresses")
                        .HasForeignKey("DressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BellaSposaBridal.Domain.Entities.Dress", "Related")
                        .WithMany()
                        .HasForeignKey("RelatedDressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dress");

                    b.Navigation("Related");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("ViewedDresses");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.Collection", b =>
                {
                    b.Navigation("DressCollections");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.Dress", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Photos");

                    b.Navigation("RelatedDresses");

                    b.Navigation("Sizes");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("BellaSposaBridal.Domain.Entities.SilhouetteType", b =>
                {
                    b.Navigation("Dresses");
                });
#pragma warning restore 612, 618
        }
    }
}
